import React, { useState, useEffect } from 'react';
import { 
  Layers, 
  RotateCw, 
  ChevronLeft, 
  ChevronRight, 
  Shuffle, 
  RefreshCw, 
  Check, 
  AlertCircle,
  Download,
  FileText
} from 'lucide-react';
import { Flashcard, StudySession } from '../types';

interface FlashcardsViewProps {
  session: StudySession;
  onUpdateSession: (updatedSession: StudySession) => void;
  theme: 'light' | 'dark';
}

export default function FlashcardsView({ session, onUpdateSession, theme }: FlashcardsViewProps) {
  const [deck, setDeck] = useState<Flashcard[]>([]);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);

  // Synchronize local state deck with session details
  useEffect(() => {
    if (session.materials?.flashcards) {
      setDeck(session.materials.flashcards);
    }
  }, [session]);

  const activeCard = deck[currentIndex];

  const triggerUpdateSession = (newDeck: Flashcard[]) => {
    setDeck(newDeck);
    const updatedSession = {
      ...session,
      materials: {
        ...session.materials,
        flashcards: newDeck
      }
    };
    onUpdateSession(updatedSession);
  };

  const handleFlip = () => {
    setIsFlipped(!isFlipped);
  };

  const handleNext = () => {
    if (currentIndex < deck.length - 1) {
      setIsFlipped(false);
      // Let flip animation clear before updating content
      setTimeout(() => {
        setCurrentIndex(currentIndex + 1);
      }, 150);
    }
  };

  const handlePrev = () => {
    if (currentIndex > 0) {
      setIsFlipped(false);
      setTimeout(() => {
        setCurrentIndex(currentIndex - 1);
      }, 150);
    }
  };

  const handleShuffle = () => {
    const shuffled = [...deck].sort(() => Math.random() - 0.5);
    setIsFlipped(false);
    setTimeout(() => {
      setDeck(shuffled);
      setCurrentIndex(0);
    }, 150);
  };

  const handleRestart = () => {
    const resetDeck = deck.map((card) => ({
      ...card,
      isKnown: false,
      needsReview: false
    }));
    setIsFlipped(false);
    setTimeout(() => {
      triggerUpdateSession(resetDeck);
      setCurrentIndex(0);
    }, 150);
  };

  const handleMarkKnown = () => {
    if (!activeCard) return;
    const newDeck = [...deck];
    newDeck[currentIndex] = {
      ...activeCard,
      isKnown: true,
      needsReview: false
    };
    triggerUpdateSession(newDeck);
    // Auto advance
    if (currentIndex < deck.length - 1) {
      handleNext();
    }
  };

  const handleMarkReview = () => {
    if (!activeCard) return;
    const newDeck = [...deck];
    newDeck[currentIndex] = {
      ...activeCard,
      isKnown: false,
      needsReview: true
    };
    triggerUpdateSession(newDeck);
    // Auto advance
    if (currentIndex < deck.length - 1) {
      handleNext();
    }
  };

  // Deck metrics
  const knownCount = deck.filter((c) => c.isKnown).length;
  const reviewCount = deck.filter((c) => c.needsReview).length;
  const untouchedCount = deck.length - knownCount - reviewCount;
  const progressPercentage = deck.length > 0 ? Math.round(((knownCount) / deck.length) * 100) : 0;

  const handleExportTxt = () => {
    const content = `==================================================
${session.materials.title.toUpperCase()} - FLASHCARDS
Generated by Note2Card
==================================================

${deck.map((card, i) => `[CARD ${i + 1}]
Q: ${card.question}
A: ${card.answer}
--------------------------------------------------`).join('\n\n')}

==================================================
wizardclipper12@gmail.com
==================================================`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${session.materials.title.toLowerCase().replace(/\s+/g, '_')}_flashcards.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleExportPdf = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Please allow popups to export PDFs.');
      return;
    }

    const htmlContent = `
      <html>
        <head>
          <title>${session.materials.title} - Study Flashcards</title>
          <style>
            body { font-family: 'Helvetica Neue', Arial, sans-serif; padding: 40px; color: #1f2937; background-color: #f9fafb; }
            h1 { font-size: 24px; color: #4f46e5; border-bottom: 2px solid #e5e7eb; padding-bottom: 12px; margin-bottom: 30px; text-align: center; }
            .grid { display: grid; grid-template-cols: 1fr 1fr; gap: 20px; }
            .card { background: white; border: 1px solid #e5e7eb; border-radius: 12px; padding: 24px; box-shadow: 0 1px 3px rgba(0,0,0,0.05); min-height: 180px; display: flex; flex-direction: column; justify-content: space-between; page-break-inside: avoid; }
            .header { font-size: 11px; font-weight: bold; text-transform: uppercase; color: #9ca3af; border-bottom: 1px solid #f3f4f6; padding-bottom: 6px; margin-bottom: 12px; }
            .question { font-size: 14px; font-weight: bold; color: #111827; margin-bottom: 12px; }
            .answer { font-size: 13px; color: #4b5563; border-top: 1px dashed #e5e7eb; padding-top: 12px; }
            .footer { text-align: center; font-size: 11px; color: #9ca3af; margin-top: 40px; }
          </style>
        </head>
        <body>
          <h1>Flashcards: ${session.materials.title}</h1>
          <div class="grid">
            ${deck.map((card, i) => `
              <div class="card">
                <div>
                  <div class="header">Card ${i + 1}</div>
                  <div class="question">Q: ${card.question}</div>
                </div>
                <div class="answer">A: ${card.answer}</div>
              </div>
            `).join('')}
          </div>
          <div class="footer">Generated via Note2Card - wizardclipper12@gmail.com</div>
          <script>
            window.onload = function() { window.print(); }
          </script>
        </body>
      </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
  };

  if (deck.length === 0) {
    return (
      <div className="text-center py-12">
        <p className="text-sm text-neutral-500">Loading flashcards...</p>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto py-6 px-4 md:px-6 mb-16">
      
      {/* Header Panel */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
        <div>
          <span className="text-xs font-bold text-indigo-600 dark:text-indigo-400 tracking-wider uppercase">
            Study Cards
          </span>
          <h2 className={`text-2xl md:text-3xl font-extrabold ${
            theme === 'dark' ? 'text-white' : 'text-neutral-900'
          } tracking-tight mt-1`}>
            Active Flashcard Deck
          </h2>
        </div>

        {/* Action Controls */}
        <div className="flex items-center gap-2.5 shrink-0">
          <button
            onClick={handleExportTxt}
            className={`px-3 py-2 rounded-xl border text-xs font-bold flex items-center gap-1.5 cursor-pointer transition-all ${
              theme === 'dark'
                ? 'bg-neutral-800 border-neutral-700 hover:bg-neutral-700 text-white'
                : 'bg-white border-neutral-200 hover:bg-neutral-50 text-neutral-700'
            }`}
          >
            <Download className="w-4 h-4" />
            <span>Export TXT</span>
          </button>
          
          <button
            onClick={handleExportPdf}
            className="px-3 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold flex items-center gap-1.5 shadow-sm shadow-indigo-100 dark:shadow-none cursor-pointer hover:scale-[1.01] transition-all"
          >
            <FileText className="w-4 h-4" />
            <span>Export PDF</span>
          </button>
        </div>
      </div>

      {/* Analytics Progress Board */}
      <div className={`grid grid-cols-2 md:grid-cols-4 gap-4 p-5 rounded-2xl border ${
        theme === 'dark' ? 'bg-neutral-900 border-neutral-800' : 'bg-white border-neutral-200'
      } shadow-sm mb-8`}>
        
        {/* Progress percent */}
        <div className="flex flex-col justify-between">
          <span className="text-[10px] uppercase font-bold text-neutral-400">Mastery Progress</span>
          <div className="flex items-baseline gap-1 mt-1">
            <span className={`text-2xl font-black ${theme === 'dark' ? 'text-white' : 'text-neutral-800'}`}>
              {progressPercentage}%
            </span>
            <span className="text-xs text-neutral-400 font-semibold">Mastered</span>
          </div>
          <div className="w-full bg-neutral-100 dark:bg-neutral-800 rounded-full h-1.5 overflow-hidden mt-2">
            <div 
              className="bg-emerald-500 h-1.5 rounded-full transition-all duration-300" 
              style={{ width: `${progressPercentage}%` }}
            ></div>
          </div>
        </div>

        {/* Known Cards */}
        <div className="border-l border-neutral-100 dark:border-neutral-800/60 pl-4">
          <span className="text-[10px] uppercase font-bold text-emerald-500">Mastered (Known)</span>
          <p className={`text-2xl font-black mt-1 ${theme === 'dark' ? 'text-white' : 'text-neutral-800'}`}>
            {knownCount}
          </p>
          <span className="text-[10px] text-neutral-400 font-medium">Keep it up!</span>
        </div>

        {/* Review Cards */}
        <div className="border-l border-neutral-100 dark:border-neutral-800/60 pl-4">
          <span className="text-[10px] uppercase font-bold text-amber-500">Needs Review</span>
          <p className={`text-2xl font-black mt-1 ${theme === 'dark' ? 'text-white' : 'text-neutral-800'}`}>
            {reviewCount}
          </p>
          <span className="text-[10px] text-neutral-400 font-medium">Will test later</span>
        </div>

        {/* Remaining */}
        <div className="border-l border-neutral-100 dark:border-neutral-800/60 pl-4">
          <span className="text-[10px] uppercase font-bold text-indigo-500">Untouched</span>
          <p className={`text-2xl font-black mt-1 ${theme === 'dark' ? 'text-white' : 'text-neutral-800'}`}>
            {untouchedCount}
          </p>
          <span className="text-[10px] text-neutral-400 font-medium">Out of {deck.length} total</span>
        </div>

      </div>

      {/* Main Flashcard Body */}
      {activeCard && (
        <div className="space-y-6">
          
          {/* Flipped Card Interface */}
          <div 
            onClick={handleFlip}
            className="card-flip w-full min-h-[340px] md:min-h-[380px] cursor-pointer"
            id={`btn-flip-card-${activeCard.id}`}
          >
            <div className={`card-flip-inner w-full h-full min-h-[340px] md:min-h-[380px] relative rounded-2xl border transition-all duration-300 ${
              isFlipped ? 'card-flip-back' : ''
            } ${
              theme === 'dark' 
                ? 'bg-neutral-900 border-neutral-800' 
                : 'bg-white border-neutral-200 shadow-sm hover:shadow-md'
            }`}>
              
              {/* CARD FRONT: Question */}
              <div className="backface-hidden absolute inset-0 p-8 flex flex-col justify-between">
                <div>
                  <div className="flex justify-between items-center pb-4 border-b border-neutral-100 dark:border-neutral-800">
                    <span className="text-xs uppercase tracking-wider font-bold text-indigo-600 dark:text-indigo-400 flex items-center gap-1">
                      <Layers className="w-3.5 h-3.5" />
                      <span>Question • {currentIndex + 1} of {deck.length}</span>
                    </span>
                    {activeCard.isKnown && (
                      <span className="text-[10px] uppercase tracking-wider font-extrabold bg-emerald-50 dark:bg-emerald-950/40 text-emerald-600 dark:text-emerald-400 px-2 py-0.5 rounded">
                        Mastered
                      </span>
                    )}
                    {activeCard.needsReview && (
                      <span className="text-[10px] uppercase tracking-wider font-extrabold bg-amber-50 dark:bg-amber-950/40 text-amber-600 dark:text-amber-400 px-2 py-0.5 rounded">
                        Needs Review
                      </span>
                    )}
                  </div>
                  
                  <div className="py-10 text-center">
                    <h3 className={`text-lg md:text-xl font-bold tracking-tight leading-relaxed px-4 ${
                      theme === 'dark' ? 'text-white' : 'text-neutral-900'
                    }`}>
                      {activeCard.question}
                    </h3>
                  </div>
                </div>

                <div className="text-center text-neutral-400 text-xs font-semibold flex items-center justify-center gap-1.5">
                  <RotateCw className="w-4 h-4 animate-pulse text-indigo-500" />
                  <span>Tap card to reveal answer</span>
                </div>
              </div>

              {/* CARD BACK: Answer */}
              <div className="backface-hidden card-flip-back absolute inset-0 p-8 flex flex-col justify-between">
                <div>
                  <div className="flex justify-between items-center pb-4 border-b border-neutral-100 dark:border-neutral-800">
                    <span className="text-xs uppercase tracking-wider font-bold text-emerald-600 dark:text-emerald-400 flex items-center gap-1">
                      <Layers className="w-3.5 h-3.5" />
                      <span>Answer • {currentIndex + 1} of {deck.length}</span>
                    </span>
                    <span className="text-[10px] uppercase tracking-wider font-extrabold bg-neutral-100 dark:bg-neutral-800 text-neutral-400 px-2 py-0.5 rounded">
                      Flipped
                    </span>
                  </div>

                  <div className="py-10 text-center">
                    <p className={`text-base font-semibold leading-relaxed px-4 ${
                      theme === 'dark' ? 'text-neutral-300' : 'text-neutral-700'
                    }`}>
                      {activeCard.answer}
                    </p>
                  </div>
                </div>

                <div className="text-center text-neutral-400 text-xs font-semibold flex items-center justify-center gap-1.5">
                  <RotateCw className="w-4 h-4 text-emerald-500" />
                  <span>Tap card to return to question</span>
                </div>
              </div>

            </div>
          </div>

          {/* Known / Needs Review tactile controls */}
          <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
            <button
              onClick={handleMarkReview}
              className={`w-full sm:w-auto px-6 py-3 rounded-xl border text-xs font-bold flex items-center justify-center gap-2 cursor-pointer transition-all hover:scale-[1.01] ${
                theme === 'dark'
                  ? 'bg-neutral-900 border-neutral-800 hover:bg-neutral-800 text-amber-500'
                  : 'bg-white border-neutral-200 hover:bg-neutral-50 text-amber-600'
              }`}
              id="btn-mark-review"
            >
              <AlertCircle className="w-4.5 h-4.5 text-amber-500" />
              <span>Needs Review</span>
            </button>

            <button
              onClick={handleMarkKnown}
              className="w-full sm:w-auto px-6 py-3 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold flex items-center justify-center gap-2 cursor-pointer hover:scale-[1.01] transition-all"
              id="btn-mark-known"
            >
              <Check className="w-4.5 h-4.5" />
              <span>Mark as Mastered (Known)</span>
            </button>
          </div>

          {/* Navigation Controls */}
          <div className="flex items-center justify-between border-t border-neutral-100 dark:border-neutral-800 pt-6">
            
            {/* Left side actions */}
            <div className="flex items-center gap-2">
              <button
                onClick={handleShuffle}
                className={`p-2 rounded-xl border transition-colors cursor-pointer ${
                  theme === 'dark'
                    ? 'bg-neutral-900 border-neutral-800 hover:bg-neutral-800 text-neutral-400 hover:text-white'
                    : 'bg-white border-neutral-200 hover:bg-neutral-50 text-neutral-500 hover:text-indigo-600'
                }`}
                title="Shuffle Deck"
                id="btn-shuffle-deck"
              >
                <Shuffle className="w-4.5 h-4.5" />
              </button>
              
              <button
                onClick={handleRestart}
                className={`p-2 rounded-xl border transition-colors cursor-pointer ${
                  theme === 'dark'
                    ? 'bg-neutral-900 border-neutral-800 hover:bg-neutral-800 text-neutral-400 hover:text-white'
                    : 'bg-white border-neutral-200 hover:bg-neutral-50 text-neutral-500 hover:text-indigo-600'
                }`}
                title="Restart Deck"
                id="btn-restart-deck"
              >
                <RefreshCw className="w-4.5 h-4.5" />
              </button>
            </div>

            {/* Pagination numbers */}
            <span className="text-xs font-bold text-neutral-400">
              Card {currentIndex + 1} of {deck.length}
            </span>

            {/* Back/Next buttons */}
            <div className="flex items-center gap-2">
              <button
                onClick={handlePrev}
                disabled={currentIndex === 0}
                className={`p-2.5 rounded-xl border transition-all cursor-pointer ${
                  currentIndex === 0
                    ? 'opacity-30 cursor-not-allowed text-neutral-400'
                    : theme === 'dark'
                    ? 'bg-neutral-900 border-neutral-800 hover:bg-neutral-800 text-white'
                    : 'bg-white border-neutral-200 hover:bg-neutral-50 text-neutral-700'
                }`}
                id="btn-prev-card"
              >
                <ChevronLeft className="w-5 h-5" />
              </button>

              <button
                onClick={handleNext}
                disabled={currentIndex === deck.length - 1}
                className={`p-2.5 rounded-xl border transition-all cursor-pointer ${
                  currentIndex === deck.length - 1
                    ? 'opacity-30 cursor-not-allowed text-neutral-400'
                    : theme === 'dark'
                    ? 'bg-neutral-900 border-neutral-800 hover:bg-neutral-800 text-white'
                    : 'bg-white border-neutral-200 hover:bg-neutral-50 text-neutral-700'
                }`}
                id="btn-next-card"
              >
                <ChevronRight className="w-5 h-5" />
              </button>
            </div>

          </div>

        </div>
      )}

    </div>
  );
}
