import React, { useState, useEffect } from 'react';
import { 
  HelpCircle, 
  CheckCircle2, 
  XCircle, 
  ChevronRight, 
  RefreshCw, 
  BookOpen, 
  Download,
  FileText,
  AlertCircle
} from 'lucide-react';
import { QuizQuestion, StudySession } from '../types';

interface QuizViewProps {
  session: StudySession;
  theme: 'light' | 'dark';
}

export default function QuizView({ session, theme }: QuizViewProps) {
  const [questions, setQuestions] = useState<QuizQuestion[]>([]);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [selectedOption, setSelectedOption] = useState<string | null>(null);
  const [typedAnswer, setTypedAnswer] = useState('');
  const [isAnswerChecked, setIsAnswerChecked] = useState(false);
  
  // Track history for results screen
  const [answersMap, setAnswersMap] = useState<Record<string, string>>({});
  const [quizComplete, setQuizComplete] = useState(false);

  useEffect(() => {
    if (session.materials?.quiz) {
      setQuestions(session.materials.quiz);
    }
  }, [session]);

  const activeQuestion = questions[currentIndex];

  const handleOptionSelect = (option: string) => {
    if (isAnswerChecked) return;
    setSelectedOption(option);
  };

  const handleCheckAnswer = () => {
    if (!activeQuestion) return;
    const answerToStore = activeQuestion.type === 'fill-blank' ? typedAnswer.trim() : selectedOption || '';
    if (!answerToStore && activeQuestion.type !== 'fill-blank') return;

    const isCorrect = answerToStore.toLowerCase() === activeQuestion.correctAnswer.toLowerCase();
    
    setAnswersMap((prev) => ({
      ...prev,
      [activeQuestion.id]: answerToStore
    }));

    setIsAnswerChecked(true);
  };

  const handleNext = () => {
    if (currentIndex < questions.length - 1) {
      setCurrentIndex(currentIndex + 1);
      setSelectedOption(null);
      setTypedAnswer('');
      setIsAnswerChecked(false);
    } else {
      setQuizComplete(true);
    }
  };

  const handleRetry = () => {
    setCurrentIndex(0);
    setSelectedOption(null);
    setTypedAnswer('');
    setIsAnswerChecked(false);
    setAnswersMap({});
    setQuizComplete(false);
  };

  // Calculations for results dashboard
  const getCorrectCount = () => {
    let correct = 0;
    questions.forEach((q) => {
      const uAns = answersMap[q.id] || '';
      if (uAns.toLowerCase() === q.correctAnswer.toLowerCase()) {
        correct++;
      }
    });
    return correct;
  };

  const correctCount = getCorrectCount();
  const percentage = questions.length > 0 ? Math.round((correctCount / questions.length) * 100) : 0;

  const handleExportTxt = () => {
    const content = `==================================================
${session.materials.title.toUpperCase()} - STUDY QUIZ
Generated by Note2Card
==================================================

${questions.map((q, i) => `[QUESTION ${i + 1}] (${q.type})
Q: ${q.question}
${q.options ? q.options.map((opt, oIdx) => `${String.fromCharCode(65 + oIdx)}) ${opt}`).join('\n') : ''}

Correct Answer: ${q.correctAnswer}
Explanation: ${q.explanation}
--------------------------------------------------`).join('\n\n')}

==================================================
wizardclipper12@gmail.com
==================================================`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${session.materials.title.toLowerCase().replace(/\s+/g, '_')}_quiz.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleExportPdf = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Please allow popups to export PDFs.');
      return;
    }

    const htmlContent = `
      <html>
        <head>
          <title>${session.materials.title} - Study Quiz</title>
          <style>
            body { font-family: 'Helvetica Neue', Arial, sans-serif; padding: 40px; color: #1f2937; }
            h1 { font-size: 24px; color: #4f46e5; border-bottom: 2px solid #e5e7eb; padding-bottom: 12px; margin-bottom: 30px; }
            .question-box { margin-bottom: 32px; page-break-inside: avoid; border-bottom: 1px solid #f3f4f6; padding-bottom: 20px; }
            .question-text { font-size: 15px; font-weight: bold; color: #111827; margin-bottom: 12px; }
            .option { font-size: 13px; color: #4b5563; margin-left: 20px; margin-bottom: 8px; }
            .answer-key { font-size: 12px; color: #059669; font-weight: bold; margin-top: 12px; background: #ecfdf5; padding: 8px; border-radius: 6px; }
            .explanation { font-size: 12px; color: #6b7280; margin-top: 6px; font-style: italic; }
            .footer { text-align: center; font-size: 11px; color: #9ca3af; margin-top: 50px; }
          </style>
        </head>
        <body>
          <h1>Quiz Sheet: ${session.materials.title}</h1>
          ${questions.map((q, i) => `
            <div class="question-box">
              <div class="question-text">${i + 1}. ${q.question}</div>
              ${q.options ? q.options.map((opt, oIdx) => `
                <div class="option">${String.fromCharCode(65 + oIdx)}) ${opt}</div>
              `).join('') : '<div class="option">________________________________________</div>'}
              <div class="answer-key">Correct Answer: ${q.correctAnswer}</div>
              <div class="explanation">Explanation: ${q.explanation}</div>
            </div>
          `).join('')}
          <div class="footer">Generated via Note2Card - wizardclipper12@gmail.com</div>
          <script>
            window.onload = function() { window.print(); }
          </script>
        </body>
      </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
  };

  if (questions.length === 0) {
    return (
      <div className="text-center py-12">
        <p className="text-sm text-neutral-500">Loading study quiz...</p>
      </div>
    );
  }

  return (
    <div className="max-w-3xl mx-auto py-6 px-4 md:px-6 mb-16">
      
      {/* Header Panel */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
        <div>
          <span className="text-xs font-bold text-indigo-600 dark:text-indigo-400 tracking-wider uppercase">
            Test Your Knowledge
          </span>
          <h2 className={`text-2xl md:text-3xl font-extrabold ${
            theme === 'dark' ? 'text-white' : 'text-neutral-900'
          } tracking-tight mt-1`}>
            Interactive Practice Quiz
          </h2>
        </div>

        {/* Action Controls */}
        <div className="flex items-center gap-2.5 shrink-0">
          <button
            onClick={handleExportTxt}
            className={`px-3 py-2 rounded-xl border text-xs font-bold flex items-center gap-1.5 cursor-pointer transition-all ${
              theme === 'dark'
                ? 'bg-neutral-800 border-neutral-700 hover:bg-neutral-700 text-white'
                : 'bg-white border-neutral-200 hover:bg-neutral-50 text-neutral-700'
            }`}
          >
            <Download className="w-4 h-4" />
            <span>Export TXT</span>
          </button>
          
          <button
            onClick={handleExportPdf}
            className="px-3 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold flex items-center gap-1.5 shadow-sm shadow-indigo-100 dark:shadow-none cursor-pointer hover:scale-[1.01] transition-all"
          >
            <FileText className="w-4 h-4" />
            <span>Export PDF</span>
          </button>
        </div>
      </div>

      {!quizComplete ? (
        activeQuestion && (
          <div className="space-y-6">
            
            {/* Progress Bar Header */}
            <div className="flex justify-between items-center text-xs font-bold text-neutral-400">
              <span>Question {currentIndex + 1} of {questions.length}</span>
              <span className="capitalize tracking-wider bg-neutral-100 dark:bg-neutral-800 px-2 py-0.5 rounded">
                {activeQuestion.type.replace('-', ' ')}
              </span>
            </div>
            
            <div className="w-full bg-neutral-100 dark:bg-neutral-800 rounded-full h-1.5 overflow-hidden">
              <div 
                className="bg-indigo-600 h-1.5 rounded-full transition-all duration-300" 
                style={{ width: `${((currentIndex) / questions.length) * 100}%` }}
              ></div>
            </div>

            {/* Question Card */}
            <div className={`p-6 md:p-8 rounded-2xl border ${
              theme === 'dark' ? 'bg-neutral-900 border-neutral-800' : 'bg-white border-neutral-200'
            } shadow-sm space-y-6`}>
              
              <h3 className={`text-base md:text-lg font-bold leading-relaxed ${
                theme === 'dark' ? 'text-white' : 'text-neutral-900'
              }`}>
                {activeQuestion.question}
              </h3>

              {/* Multiple Choice Options */}
              {activeQuestion.type === 'multiple-choice' && activeQuestion.options && (
                <div className="grid grid-cols-1 gap-3">
                  {activeQuestion.options.map((option, idx) => {
                    const isSelected = selectedOption === option;
                    const isCorrect = option.toLowerCase() === activeQuestion.correctAnswer.toLowerCase();
                    
                    let cardStyle = theme === 'dark' 
                      ? 'bg-neutral-800/40 border-neutral-700 text-neutral-200 hover:bg-neutral-800'
                      : 'bg-neutral-50 border-neutral-200 text-neutral-800 hover:bg-neutral-100/60';
                    
                    if (isSelected && !isAnswerChecked) {
                      cardStyle = 'border-indigo-500 bg-indigo-50/20 text-indigo-600 dark:text-indigo-400';
                    } else if (isAnswerChecked) {
                      if (isCorrect) {
                        cardStyle = 'border-emerald-500 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 font-bold';
                      } else if (isSelected) {
                        cardStyle = 'border-rose-500 bg-rose-500/10 text-rose-600 dark:text-rose-400';
                      } else {
                        cardStyle = 'opacity-50 border-neutral-200 dark:border-neutral-800';
                      }
                    }

                    return (
                      <button
                        key={idx}
                        onClick={() => handleOptionSelect(option)}
                        disabled={isAnswerChecked}
                        className={`w-full text-left px-4 py-3.5 rounded-xl text-xs font-semibold border flex items-center gap-3 transition-all cursor-pointer ${cardStyle}`}
                      >
                        <span className={`w-6 h-6 rounded-lg flex items-center justify-center text-[10px] font-bold ${
                          isSelected 
                            ? 'bg-indigo-600 text-white' 
                            : 'bg-neutral-200 dark:bg-neutral-800 text-neutral-500'
                        }`}>
                          {String.fromCharCode(65 + idx)}
                        </span>
                        <span>{option}</span>
                      </button>
                    );
                  })}
                </div>
              )}

              {/* True/False Options */}
              {activeQuestion.type === 'true-false' && (
                <div className="grid grid-cols-2 gap-4">
                  {['True', 'False'].map((option, idx) => {
                    const isSelected = selectedOption === option;
                    const isCorrect = option.toLowerCase() === activeQuestion.correctAnswer.toLowerCase();
                    
                    let cardStyle = theme === 'dark' 
                      ? 'bg-neutral-800/40 border-neutral-700 text-neutral-200 hover:bg-neutral-800'
                      : 'bg-neutral-50 border-neutral-200 text-neutral-800 hover:bg-neutral-100/60';
                    
                    if (isSelected && !isAnswerChecked) {
                      cardStyle = 'border-indigo-500 bg-indigo-50/20 text-indigo-600 dark:text-indigo-400';
                    } else if (isAnswerChecked) {
                      if (isCorrect) {
                        cardStyle = 'border-emerald-500 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 font-bold';
                      } else if (isSelected) {
                        cardStyle = 'border-rose-500 bg-rose-500/10 text-rose-600 dark:text-rose-400';
                      } else {
                        cardStyle = 'opacity-50 border-neutral-200 dark:border-neutral-800';
                      }
                    }

                    return (
                      <button
                        key={idx}
                        onClick={() => handleOptionSelect(option)}
                        disabled={isAnswerChecked}
                        className={`py-4 rounded-xl border text-center font-bold text-xs cursor-pointer transition-all ${cardStyle}`}
                      >
                        {option}
                      </button>
                    );
                  })}
                </div>
              )}

              {/* Fill in the Blank Form */}
              {activeQuestion.type === 'fill-blank' && (
                <div>
                  <input
                    type="text"
                    value={typedAnswer}
                    onChange={(e) => setTypedAnswer(e.target.value)}
                    disabled={isAnswerChecked}
                    placeholder="Type your answer here..."
                    className={`w-full px-4 py-3.5 rounded-xl border text-xs font-semibold focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition-all ${
                      theme === 'dark'
                        ? 'bg-neutral-800 border-neutral-700 text-white placeholder-neutral-500'
                        : 'bg-neutral-50 border-neutral-200 text-neutral-800 placeholder-neutral-400'
                    }`}
                  />
                </div>
              )}

              {/* Feedback Alert Section */}
              {isAnswerChecked && (
                <div className={`p-4 rounded-xl border space-y-2 mt-4 transition-all duration-300 animate-fadeIn ${
                  (activeQuestion.type === 'fill-blank' ? typedAnswer.trim().toLowerCase() : selectedOption?.toLowerCase()) === activeQuestion.correctAnswer.toLowerCase()
                    ? 'bg-emerald-50 dark:bg-emerald-950/30 border-emerald-500/30 text-emerald-800 dark:text-emerald-400'
                    : 'bg-rose-50 dark:bg-rose-950/30 border-rose-500/30 text-rose-800 dark:text-rose-400'
                }`}>
                  <div className="flex items-center gap-2">
                    {(activeQuestion.type === 'fill-blank' ? typedAnswer.trim().toLowerCase() : selectedOption?.toLowerCase()) === activeQuestion.correctAnswer.toLowerCase() ? (
                      <>
                        <CheckCircle2 className="w-5 h-5 text-emerald-500" />
                        <span className="text-xs font-bold uppercase">Correct Answer!</span>
                      </>
                    ) : (
                      <>
                        <XCircle className="w-5 h-5 text-rose-500" />
                        <span className="text-xs font-bold uppercase">Incorrect Answer</span>
                      </>
                    )}
                  </div>
                  <p className="text-xs leading-relaxed font-medium">
                    <strong className="block mb-1 text-neutral-700 dark:text-neutral-300">Correct Answer: {activeQuestion.correctAnswer}</strong>
                    {activeQuestion.explanation}
                  </p>
                </div>
              )}

            </div>

            {/* Pagination / Check / Next controls */}
            <div className="flex justify-end pt-2">
              {!isAnswerChecked ? (
                <button
                  onClick={handleCheckAnswer}
                  disabled={activeQuestion.type === 'fill-blank' ? !typedAnswer.trim() : !selectedOption}
                  className={`px-6 py-3 rounded-xl text-xs font-bold shadow-sm transition-all cursor-pointer flex items-center gap-1.5 ${
                    (activeQuestion.type === 'fill-blank' ? !typedAnswer.trim() : !selectedOption)
                      ? 'bg-neutral-200 dark:bg-neutral-800 text-neutral-400 cursor-not-allowed shadow-none'
                      : 'bg-indigo-600 hover:bg-indigo-700 text-white hover:scale-[1.01]'
                  }`}
                  id="btn-check-quiz-answer"
                >
                  <span>Check Answer</span>
                </button>
              ) : (
                <button
                  onClick={handleNext}
                  className="px-6 py-3 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold shadow-sm hover:scale-[1.01] flex items-center gap-1.5 transition-all cursor-pointer"
                  id="btn-next-quiz-question"
                >
                  <span>{currentIndex === questions.length - 1 ? 'Finish Quiz' : 'Next Question'}</span>
                  <ChevronRight className="w-4 h-4" />
                </button>
              )}
            </div>

          </div>
        )
      ) : (
        /* Final results dashboard page */
        <div className="space-y-6">
          <div className={`p-8 rounded-2xl border text-center ${
            theme === 'dark' ? 'bg-neutral-900 border-neutral-800' : 'bg-white border-neutral-200'
          } shadow-sm space-y-4`}>
            
            <span className="text-xs uppercase tracking-wider font-extrabold text-indigo-500">
              Quiz Completed!
            </span>

            {/* Percentage graphics */}
            <div className="relative w-28 h-28 mx-auto flex items-center justify-center">
              <svg className="w-full h-full transform -rotate-90">
                <circle
                  cx="56"
                  cy="56"
                  r="48"
                  stroke={theme === 'dark' ? '#1f2937' : '#f3f4f6'}
                  strokeWidth="8"
                  fill="transparent"
                />
                <circle
                  cx="56"
                  cy="56"
                  r="48"
                  stroke="#4f46e5"
                  strokeWidth="8"
                  fill="transparent"
                  strokeDasharray={2 * Math.PI * 48}
                  strokeDashoffset={2 * Math.PI * 48 * (1 - percentage / 100)}
                  className="transition-all duration-1000"
                />
              </svg>
              <div className="absolute text-center">
                <span className={`text-xl font-black ${theme === 'dark' ? 'text-white' : 'text-neutral-800'}`}>
                  {percentage}%
                </span>
                <p className="text-[10px] text-neutral-400 font-bold">{correctCount}/{questions.length}</p>
              </div>
            </div>

            <h3 className={`text-lg font-bold ${theme === 'dark' ? 'text-white' : 'text-neutral-900'}`}>
              {percentage >= 90
                ? 'Outstanding performance! A+ Masterclass!'
                : percentage >= 70
                ? 'Great score! Solid understanding of the material.'
                : 'Good effort, keep practicing to strengthen retention.'}
            </h3>

            {/* Control triggers */}
            <div className="pt-2 flex justify-center">
              <button
                onClick={handleRetry}
                className="px-6 py-3 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold shadow-md hover:scale-[1.01] flex items-center gap-1.5 transition-all cursor-pointer"
                id="btn-retry-quiz"
              >
                <RefreshCw className="w-4 h-4 animate-spin" style={{ animationDuration: '6s' }} />
                <span>Retry Quiz</span>
              </button>
            </div>

          </div>

          {/* Review Incorrect Answers */}
          <div className="space-y-4">
            <h4 className={`text-sm font-bold ${theme === 'dark' ? 'text-white' : 'text-neutral-800'}`}>
              Detailed Question Review
            </h4>

            <div className="space-y-4">
              {questions.map((q, idx) => {
                const uAns = answersMap[q.id] || '';
                const isCorrect = uAns.toLowerCase() === q.correctAnswer.toLowerCase();

                return (
                  <div
                    key={q.id}
                    className={`p-5 rounded-xl border ${
                      isCorrect
                        ? theme === 'dark' ? 'bg-neutral-900/40 border-emerald-950 text-neutral-300' : 'bg-emerald-50/10 border-emerald-100 text-neutral-700'
                        : theme === 'dark' ? 'bg-neutral-900/40 border-rose-950 text-neutral-300' : 'bg-rose-50/10 border-rose-100 text-neutral-700'
                    }`}
                  >
                    <div className="flex items-center gap-2 mb-2">
                      {isCorrect ? (
                        <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                      ) : (
                        <XCircle className="w-4 h-4 text-rose-500" />
                      )}
                      <span className="text-xs font-bold">Question {idx + 1}</span>
                    </div>

                    <p className={`text-xs font-bold ${theme === 'dark' ? 'text-white' : 'text-neutral-800'}`}>{q.question}</p>
                    
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-2 mt-3 text-[11px] font-semibold">
                      <div className="p-2 rounded bg-neutral-100 dark:bg-neutral-800 text-neutral-500">
                        <span>Your Answer: </span>
                        <strong className={isCorrect ? 'text-emerald-500' : 'text-rose-500'}>
                          {uAns || 'Skipped'}
                        </strong>
                      </div>

                      <div className="p-2 rounded bg-emerald-50 dark:bg-emerald-950/20 text-emerald-600 dark:text-emerald-400">
                        <span>Correct Answer: </span>
                        <strong>{q.correctAnswer}</strong>
                      </div>
                    </div>

                    <p className="text-[11px] font-medium leading-relaxed mt-3 pt-2.5 border-t border-neutral-100 dark:border-neutral-800 text-neutral-400">
                      <strong>Explanation: </strong>
                      {q.explanation}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
