import React, { useState } from 'react';
import { 
  FileText, 
  Search, 
  Download, 
  BookOpen, 
  Layers, 
  AlertCircle, 
  HelpCircle, 
  Key, 
  Compass, 
  Lightbulb,
  CheckCircle,
  Hash
} from 'lucide-react';
import { StudySession } from '../types';

interface SummaryViewProps {
  session: StudySession;
  theme: 'light' | 'dark';
}

export default function SummaryView({ session, theme }: SummaryViewProps) {
  const [searchQuery, setSearchQuery] = useState('');
  const [activeTab, setActiveTab] = useState<'all' | 'summary' | 'outline' | 'concepts' | 'tips'>('all');

  const { materials } = session;

  const handleExportTxt = () => {
    const content = `==================================================
${materials.title.toUpperCase()} - STUDY SUMMARY
Generated by Note2Card
==================================================

1. EXECUTIVE SUMMARY
${materials.summary}

2. KEY TAKEAWAYS
${materials.keyPoints.map((p, i) => `- ${p}`).join('\n')}

3. CHAPTER OUTLINE
${materials.chapterOutline.map((c) => `Chapter: ${c.chapter}\nDetails: ${c.details}\n`).join('\n')}

4. IMPORTANT CONCEPTS
${materials.importantConcepts.map((c) => `- ${c.concept}: ${c.explanation}`).join('\n')}

5. DEFINITIONS & KEY TERMS
${materials.definitions.map((d) => `- ${d.term}: ${d.definition}`).join('\n')}

6. DETAILED STUDY NOTES
${materials.studyNotes.map((n, i) => `[Topic ${i + 1}] ${n}`).join('\n\n')}

7. EXAM PREPARATION TIPS
${materials.examTips.map((t) => `- ${t}`).join('\n')}

8. MEMORY MNEMONICS & TRICKS
${materials.memoryTricks.map((t) => `- ${t}`).join('\n')}

9. FREQUENTLY TESTED TOPICS
${materials.frequentlyTested.map((t) => `- ${t}`).join('\n')}

==================================================
Study Material created on Note2Card
wizardclipper12@gmail.com
==================================================`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${materials.title.toLowerCase().replace(/\s+/g, '_')}_summary.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleExportPdf = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Please allow popups to export PDFs.');
      return;
    }

    const htmlContent = `
      <html>
        <head>
          <title>${materials.title} - Study Summary</title>
          <style>
            body { font-family: 'Helvetica Neue', Arial, sans-serif; padding: 40px; color: #1f2937; line-height: 1.6; }
            h1 { font-size: 28px; color: #4f46e5; border-bottom: 2px solid #e5e7eb; padding-bottom: 12px; margin-bottom: 24px; }
            h2 { font-size: 20px; color: #111827; margin-top: 32px; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; }
            h3 { font-size: 16px; color: #374151; margin-top: 20px; }
            p, li { font-size: 14px; margin-bottom: 10px; }
            ul { padding-left: 20px; margin-bottom: 20px; }
            .badge { display: inline-block; background-color: #f3f4f6; color: #4b5563; font-size: 11px; font-weight: bold; padding: 3px 8px; rounded: 4px; margin-bottom: 20px; text-transform: uppercase; }
            .box { background-color: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin-bottom: 20px; }
            .tip-box { background-color: #fffbeb; border-left: 4px solid #f59e0b; padding: 12px; border-radius: 0 8px 8px 0; margin-bottom: 16px; }
            .footer { margin-top: 60px; font-size: 11px; text-align: center; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 20px; }
          </style>
        </head>
        <body>
          <h1>${materials.title}</h1>
          <div class="badge">Study Summary Dashboard</div>
          
          <h2>1. Executive Summary</h2>
          <p>${materials.summary.replace(/\n/g, '<br>')}</p>

          <h2>2. Key Takeaways</h2>
          <ul>
            ${materials.keyPoints.map(p => `<li>${p}</li>`).join('')}
          </ul>

          <h2>3. Chapter Outline</h2>
          ${materials.chapterOutline.map(c => `
            <div class="box">
              <h3>${c.chapter}</h3>
              <p>${c.details}</p>
            </div>
          `).join('')}

          <h2>4. Core Concepts Explained</h2>
          <ul>
            ${materials.importantConcepts.map(c => `<li><strong>${c.concept}:</strong> ${c.explanation}</li>`).join('')}
          </ul>

          <h2>5. Definitions & Glossary</h2>
          <ul>
            ${materials.definitions.map(d => `<li><strong>${d.term}:</strong> ${d.definition}</li>`).join('')}
          </ul>

          <h2>6. Study Notes</h2>
          <ul>
            ${materials.studyNotes.map(n => `<li>${n}</li>`).join('')}
          </ul>

          <h2>7. Exam Tips</h2>
          ${materials.examTips.map(t => `<div class="tip-box"><strong>Tip:</strong> ${t}</div>`).join('')}

          <h2>8. Memory Mnemonics & Tricks</h2>
          <ul>
            ${materials.memoryTricks.map(t => `<li>${t}</li>`).join('')}
          </ul>

          <h2>9. Frequently Tested Topics</h2>
          <ul>
            ${materials.frequentlyTested.map(t => `<li><strong>Highly Probable:</strong> ${t}</li>`).join('')}
          </ul>

          <div class="footer">
            Generated via Note2Card - wizardclipper12@gmail.com
          </div>
          <script>
            window.onload = function() { window.print(); }
          </script>
        </body>
      </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
  };

  // Safe keyword search helper
  const matchesSearch = (text: string) => {
    if (!searchQuery) return true;
    return text.toLowerCase().includes(searchQuery.toLowerCase());
  };

  const filteredConcepts = materials.importantConcepts.filter(
    (c) => matchesSearch(c.concept) || matchesSearch(c.explanation)
  );

  const filteredDefinitions = materials.definitions.filter(
    (d) => matchesSearch(d.term) || matchesSearch(d.definition)
  );

  const filteredOutline = materials.chapterOutline.filter(
    (o) => matchesSearch(o.chapter) || matchesSearch(o.details)
  );

  return (
    <div className="max-w-5xl mx-auto py-6 px-4 md:px-6 mb-16">
      
      {/* Upper Panel */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
        <div>
          <span className="text-xs font-bold text-indigo-600 dark:text-indigo-400 tracking-wider uppercase">
            Active Study Material
          </span>
          <h2 className={`text-2xl md:text-3xl font-extrabold ${
            theme === 'dark' ? 'text-white' : 'text-neutral-900'
          } tracking-tight mt-1`}>
            {materials.title}
          </h2>
        </div>

        {/* Action Controls */}
        <div className="flex items-center gap-2.5 shrink-0">
          <button
            onClick={handleExportTxt}
            className={`px-3 py-2 rounded-xl border text-xs font-bold flex items-center gap-1.5 cursor-pointer transition-all ${
              theme === 'dark'
                ? 'bg-neutral-800 border-neutral-700 hover:bg-neutral-700 text-white'
                : 'bg-white border-neutral-200 hover:bg-neutral-50 text-neutral-700'
            }`}
          >
            <Download className="w-4 h-4" />
            <span>Export TXT</span>
          </button>
          
          <button
            onClick={handleExportPdf}
            className="px-3 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold flex items-center gap-1.5 shadow-sm shadow-indigo-100 dark:shadow-none cursor-pointer hover:scale-[1.01] transition-all"
          >
            <FileText className="w-4 h-4" />
            <span>Export PDF</span>
          </button>
        </div>
      </div>

      {/* Search & Tabs Filter */}
      <div className={`p-4 rounded-2xl border ${
        theme === 'dark' ? 'bg-neutral-900 border-neutral-800' : 'bg-white border-neutral-200'
      } mb-8 shadow-sm space-y-4`}>
        
        {/* Search Bar */}
        <div className="relative">
          <Search className="w-4.5 h-4.5 absolute left-3.5 top-3.5 text-neutral-400" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search keywords within summary, glossary terms, or key concepts..."
            className={`w-full pl-11 pr-4 py-3 rounded-xl text-xs font-semibold border focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition-all ${
              theme === 'dark'
                ? 'bg-neutral-800 border-neutral-700 text-white'
                : 'bg-neutral-50 border-neutral-200 text-neutral-800'
            }`}
          />
        </div>

        {/* Categories Tab Selector */}
        <div className="flex flex-wrap gap-2 pt-1 border-t border-neutral-100 dark:border-neutral-800">
          {[
            { id: 'all', label: 'All Resources', icon: BookOpen },
            { id: 'summary', label: 'Executive Summary', icon: FileText },
            { id: 'outline', label: 'Course Outline', icon: Compass },
            { id: 'concepts', label: 'Concepts & Glossary', icon: Key },
            { id: 'tips', label: 'Exam Study Guides', icon: Lightbulb }
          ].map((tab) => {
            const Icon = tab.icon;
            const active = activeTab === tab.id;
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id as any)}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold flex items-center gap-1.5 transition-all cursor-pointer ${
                  active
                    ? 'bg-indigo-600 text-white'
                    : theme === 'dark'
                    ? 'text-neutral-400 hover:bg-neutral-800'
                    : 'text-neutral-600 hover:bg-neutral-100'
                }`}
              >
                <Icon className="w-3.5 h-3.5" />
                <span>{tab.label}</span>
              </button>
            );
          })}
        </div>
      </div>

      {/* Main Grid Content */}
      <div className="space-y-8">
        
        {/* Executive Summary */}
        {(activeTab === 'all' || activeTab === 'summary') && (
          <div className={`p-6 md:p-8 rounded-2xl border ${
            theme === 'dark' ? 'bg-neutral-900 border-neutral-800' : 'bg-white border-neutral-200'
          } shadow-xs`}>
            <div className="flex items-center gap-2 mb-4">
              <BookOpen className="w-5.5 h-5.5 text-indigo-500" />
              <h3 className={`text-lg font-bold ${theme === 'dark' ? 'text-white' : 'text-neutral-900'}`}>
                1. Executive Summary
              </h3>
            </div>
            
            <p className={`text-sm leading-relaxed whitespace-pre-wrap ${
              theme === 'dark' ? 'text-neutral-300' : 'text-neutral-700'
            } font-medium`}>
              {materials.summary}
            </p>

            {materials.keyPoints.length > 0 && (
              <div className="mt-6 pt-6 border-t border-neutral-100 dark:border-neutral-800">
                <h4 className={`text-sm font-bold ${theme === 'dark' ? 'text-neutral-200' : 'text-neutral-800'} mb-3`}>
                  Core Takeaways & Learnings
                </h4>
                <ul className="grid grid-cols-1 md:grid-cols-2 gap-3.5">
                  {materials.keyPoints.map((point, index) => (
                    <li key={index} className="flex items-start gap-2 text-xs font-semibold text-neutral-500 dark:text-neutral-400">
                      <CheckCircle className="w-4 h-4 text-emerald-500 shrink-0 mt-0.5" />
                      <span>{point}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}

        {/* Chapter Outline */}
        {(activeTab === 'all' || activeTab === 'outline') && filteredOutline.length > 0 && (
          <div className={`p-6 md:p-8 rounded-2xl border ${
            theme === 'dark' ? 'bg-neutral-900 border-neutral-800' : 'bg-white border-neutral-200'
          } shadow-xs`}>
            <div className="flex items-center gap-2 mb-6">
              <Compass className="w-5.5 h-5.5 text-violet-500" />
              <h3 className={`text-lg font-bold ${theme === 'dark' ? 'text-white' : 'text-neutral-900'}`}>
                2. Curriculum Chapter Outline
              </h3>
            </div>

            <div className="relative border-l border-neutral-200 dark:border-neutral-800 pl-6 space-y-6 ml-3">
              {filteredOutline.map((chapter, index) => (
                <div key={index} className="relative">
                  {/* Timeline point indicator */}
                  <span className="absolute -left-[31px] top-1 w-4 h-4 rounded-full bg-violet-100 dark:bg-violet-950/80 border-2 border-violet-500 flex items-center justify-center text-[8px] font-bold text-violet-600 dark:text-violet-400">
                    {index + 1}
                  </span>
                  
                  <h4 className={`text-sm font-bold ${theme === 'dark' ? 'text-white' : 'text-neutral-800'}`}>
                    {chapter.chapter}
                  </h4>
                  <p className={`text-xs mt-1.5 font-semibold leading-relaxed ${
                    theme === 'dark' ? 'text-neutral-400' : 'text-neutral-500'
                  }`}>
                    {chapter.details}
                  </p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Important Concepts & Definitions */}
        {(activeTab === 'all' || activeTab === 'concepts') && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            
            {/* Concepts Column */}
            {filteredConcepts.length > 0 && (
              <div className={`p-6 rounded-2xl border ${
                theme === 'dark' ? 'bg-neutral-900 border-neutral-800' : 'bg-white border-neutral-200'
              } shadow-xs`}>
                <div className="flex items-center gap-2 mb-4">
                  <Key className="w-5 h-5 text-indigo-500" />
                  <h3 className={`text-base font-bold ${theme === 'dark' ? 'text-white' : 'text-neutral-900'}`}>
                    Core Concepts
                  </h3>
                </div>

                <div className="space-y-4">
                  {filteredConcepts.map((item, index) => (
                    <div key={index} className={`p-3.5 rounded-xl border ${
                      theme === 'dark' ? 'bg-neutral-800/40 border-neutral-800' : 'bg-neutral-50 border-neutral-100'
                    }`}>
                      <h4 className={`text-xs font-bold ${theme === 'dark' ? 'text-indigo-400' : 'text-indigo-600'}`}>
                        {item.concept}
                      </h4>
                      <p className={`text-xs font-medium mt-1 leading-relaxed ${
                        theme === 'dark' ? 'text-neutral-300' : 'text-neutral-600'
                      }`}>
                        {item.explanation}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Definitions Column */}
            {filteredDefinitions.length > 0 && (
              <div className={`p-6 rounded-2xl border ${
                theme === 'dark' ? 'bg-neutral-900 border-neutral-800' : 'bg-white border-neutral-200'
              } shadow-xs`}>
                <div className="flex items-center gap-2 mb-4">
                  <Hash className="w-5 h-5 text-emerald-500" />
                  <h3 className={`text-base font-bold ${theme === 'dark' ? 'text-white' : 'text-neutral-900'}`}>
                    Glossary Definitions
                  </h3>
                </div>

                <div className="space-y-4">
                  {filteredDefinitions.map((item, index) => (
                    <div key={index} className="flex items-start gap-2.5 pb-3 border-b border-neutral-100 dark:border-neutral-800/60 last:border-0 last:pb-0">
                      <div className="px-2 py-0.5 rounded bg-emerald-50 dark:bg-emerald-950/40 text-[10px] font-bold text-emerald-600 dark:text-emerald-400 shrink-0 uppercase mt-0.5">
                        Term
                      </div>
                      <div>
                        <h4 className={`text-xs font-bold ${theme === 'dark' ? 'text-white' : 'text-neutral-800'}`}>
                          {item.term}
                        </h4>
                        <p className={`text-xs font-medium mt-1 leading-relaxed ${
                          theme === 'dark' ? 'text-neutral-400' : 'text-neutral-500'
                        }`}>
                          {item.definition}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

          </div>
        )}

        {/* Detailed Study Notes */}
        {(activeTab === 'all' || activeTab === 'concepts') && materials.studyNotes.length > 0 && (
          <div className={`p-6 md:p-8 rounded-2xl border ${
            theme === 'dark' ? 'bg-neutral-900 border-neutral-800' : 'bg-white border-neutral-200'
          } shadow-xs`}>
            <div className="flex items-center gap-2 mb-4">
              <FileText className="w-5.5 h-5.5 text-blue-500" />
              <h3 className={`text-lg font-bold ${theme === 'dark' ? 'text-white' : 'text-neutral-900'}`}>
                3. Analytical Study Notes
              </h3>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {materials.studyNotes.map((note, index) => (
                <div key={index} className={`p-4 rounded-xl border ${
                  theme === 'dark' ? 'bg-neutral-800/20 border-neutral-800' : 'bg-neutral-50 border-neutral-200/50'
                }`}>
                  <span className="text-[9px] uppercase tracking-wider font-extrabold text-neutral-400 bg-neutral-200/50 dark:bg-neutral-800 px-2 py-0.5 rounded-md">
                    Note {index + 1}
                  </span>
                  <p className={`text-xs font-medium mt-2 leading-relaxed ${
                    theme === 'dark' ? 'text-neutral-300' : 'text-neutral-600'
                  }`}>
                    {note}
                  </p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Exam Tips, Mnemonics & Tricks */}
        {(activeTab === 'all' || activeTab === 'tips') && (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            
            {/* Exam preparation tips */}
            <div className={`p-5 rounded-2xl border ${
              theme === 'dark' ? 'bg-neutral-900 border-neutral-800' : 'bg-white border-neutral-200'
            }`}>
              <div className="flex items-center gap-2 mb-3">
                <Lightbulb className="w-5 h-5 text-amber-500" />
                <h4 className={`text-sm font-bold ${theme === 'dark' ? 'text-white' : 'text-neutral-800'}`}>
                  Exam Preparation Tips
                </h4>
              </div>
              <ul className="space-y-3">
                {materials.examTips.map((tip, index) => (
                  <li key={index} className="flex items-start gap-2 text-xs font-semibold text-neutral-500 dark:text-neutral-400 leading-relaxed">
                    <span className="text-amber-500 font-bold mt-0.5">•</span>
                    <span>{tip}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Memory tricks */}
            <div className={`p-5 rounded-2xl border ${
              theme === 'dark' ? 'bg-neutral-900 border-neutral-800' : 'bg-white border-neutral-200'
            }`}>
              <div className="flex items-center gap-2 mb-3">
                <Layers className="w-5 h-5 text-violet-500" />
                <h4 className={`text-sm font-bold ${theme === 'dark' ? 'text-white' : 'text-neutral-800'}`}>
                  Mnemonics & Memory Tricks
                </h4>
              </div>
              <ul className="space-y-3">
                {materials.memoryTricks.map((trick, index) => (
                  <li key={index} className="flex items-start gap-2 text-xs font-semibold text-neutral-500 dark:text-neutral-400 leading-relaxed">
                    <span className="text-violet-500 font-bold mt-0.5">•</span>
                    <span>{trick}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Frequently tested topics */}
            <div className={`p-5 rounded-2xl border ${
              theme === 'dark' ? 'bg-neutral-900 border-neutral-800' : 'bg-white border-neutral-200'
            }`}>
              <div className="flex items-center gap-2 mb-3">
                <AlertCircle className="w-5 h-5 text-rose-500" />
                <h4 className={`text-sm font-bold ${theme === 'dark' ? 'text-white' : 'text-neutral-800'}`}>
                  Frequently Tested Topics
                </h4>
              </div>
              <ul className="space-y-3">
                {materials.frequentlyTested.map((topic, index) => (
                  <li key={index} className="flex items-start gap-2 text-xs font-semibold text-neutral-500 dark:text-neutral-400 leading-relaxed">
                    <span className="text-rose-500 font-bold mt-0.5">•</span>
                    <span>{topic}</span>
                  </li>
                ))}
              </ul>
            </div>

          </div>
        )}

      </div>

    </div>
  );
}
